### ISSUE TITLE
Misspelling in workaround for GitLab Pipelines

### ISSUE THREAD

**Issue by alexnitta** [plentico/plenti.co#20]
In [https://plenti.co/docs/gitlab-piplines](https://plenti.co/docs/gitlab-piplines), there is a workaround listed for deploying to GitLab Pipelines. In the code snippet for `.gitlab-ci.yml`, there are two lines in the `script` block that reference the name of a gzipped tarball that include the string `Linux_64-bit`. However, the filename is currently spelled with a lowercase `l` in `linux`, so these commands will fail. The entire block should read like this:

```
 script:
    - wget -c $(curl -s https://api.github.com/repos/plentico/plenti/releases/latest | grep -o 'http.*linux_64-bit.tar.gz')
    - tar -zxvf *_linux_64-bit.tar.gz
    - ./plenti build
```

**Comment by jimafisk** [comment]
Great catch, thanks @alexnitta!
