### ISSUE TITLE
Distorted text on "Upgrading" docs

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti.co#8]
This was flagged to me:

> just wanted to let you know of a ‘bug’ showing up for the Plenti website on the documents page in Safari. It resolves itself on reload.

![unnamed](https://user-images.githubusercontent.com/5913244/110822422-0ad27200-825f-11eb-8dff-697fffcbe5bb.png)

Link: https://plenti.co/docs/upgrading

**Comment by stephanieluz** [comment]
Could not reproduce in Safari on iOS or Desktop.
